"""implement relationships

Revision ID: 7acd61b7cb42
Revises: 6c20518c91a5
Create Date: 2025-01-31 00:30:31.372811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7acd61b7cb42'
down_revision = '6c20518c91a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('planet_id', sa.Integer(), nullable=False))
    op.add_column('missions', sa.Column('scientist_id', sa.Integer(), nullable=False))
    op.add_column('missions', sa.Column('mission_date', sa.Date(), nullable=False))
    op.add_column('missions', sa.Column('duration_days', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_missions_planet_id_planets'), 'missions', 'planets', ['planet_id'], ['id'])
    op.create_foreign_key(op.f('fk_missions_scientist_id_scientists'), 'missions', 'scientists', ['scientist_id'], ['id'])
    op.drop_column('missions', 'name')
    op.add_column('planets', sa.Column('description', sa.Text(), nullable=False))
    op.alter_column('planets', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(op.f('uq_planets_name'), 'planets', ['name'])
    op.drop_column('planets', 'distance_from_earth')
    op.drop_column('planets', 'nearest_star')
    op.alter_column('scientists', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('scientists', 'field_of_study',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(op.f('uq_scientists_name'), 'scientists', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_scientists_name'), 'scientists', type_='unique')
    op.alter_column('scientists', 'field_of_study',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('scientists', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('planets', sa.Column('nearest_star', sa.VARCHAR(), nullable=True))
    op.add_column('planets', sa.Column('distance_from_earth', sa.INTEGER(), nullable=True))
    op.drop_constraint(op.f('uq_planets_name'), 'planets', type_='unique')
    op.alter_column('planets', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('planets', 'description')
    op.add_column('missions', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_constraint(op.f('fk_missions_scientist_id_scientists'), 'missions', type_='foreignkey')
    op.drop_constraint(op.f('fk_missions_planet_id_planets'), 'missions', type_='foreignkey')
    op.drop_column('missions', 'duration_days')
    op.drop_column('missions', 'mission_date')
    op.drop_column('missions', 'scientist_id')
    op.drop_column('missions', 'planet_id')
    # ### end Alembic commands ###
